
name: MiningMachine
version: '1.1-Command'
main: org.github.WangHongMing.miningMachine.MiningMachine

commands:
  getminingmachine:
    description: Gives you a mining machine

  removeminingmachine:
    description: "Safely removes a mining machine"
    usage: /removeminingmachine
